version: "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/postgres
    hostname: api
    depends_on:
      - db
